#!/usr/bin/env bash
# chkconfig: 2345 20 80
# description: glue server
#
# /etc/rc.d/init.d/glue-server
#
# Source function library.

if [ -f /etc/init.d/functions ]; then
. /etc/init.d/functions
fi

if [ ! -f /var/lock/subsys ]; then
  mkdir -p /var/lock/subsys
fi

if [ -f /etc/profile.d/java ]; then
 . /etc/profile.d/java
fi

if [ -f /etc/profile.d/java.sh ]; then
 . /etc/profile.d/java.sh
fi

LOCKFILE="/var/lock/subsys/glue-server"
PIDFILE="/var/run/glue-server.pid"

#setup glue home variable
if [ -z "$GLUE_HOME" ]; then
  export GLUE_HOME="/opt/glue"
fi

if [ -z "$GLUE_CONF_DIR" ]; then
  export GLUE_CONF_DIR="$GLUE_HOME/conf"
fi

LAUNCH_CLASS="org.glue.rest.Launcher"
CLIENT_CLASS="org.glue.rest.Client"

if [ -n $JAVA_HOME ]; then

 echo "No JAVA_HOME defined setting to /usr/java/latest"
 export JAVA_HOME="/usr/java/latest"

fi


JAVA=$JAVA_HOME/bin/java

if [ -z $JAVA_HEAP ]; then
 export JAVA_HEAP="-XX:PermSize=64M -XX:MaxPermSize=512M -Xmx2048m"
fi

CLASSPATH=${CLASSPATH}:$JAVA_HOME/lib/tools.jar

# so that filenames w/ spaces are handled correctly in loops below
# add libs to CLASSPATH.
CLASSPATH=${CLASSPATH}:$GLUE_HOME/lib/*;
CLASSPATH=$GLUE_CONF_DIR:$GLUE_CONF_DIR/META-INF:$CLASSPATH

JAVA_OPTS="-Xss128k -XX:+CMSClassUnloadingEnabled -XX:MaxDirectMemorySize=1024M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:SurvivorRatio=6 -XX:NewRatio=3 -XX:+DisableExplicitGC $JAVA_OPTS"



startGlueServer(){
  echo
  
  LOG="$GLUE_HOME/logs/serverlog.log"

  RUN_CMD="$JAVA $JAVA_HEAP $JAVA_OPTS -classpath "$CLASSPATH" $LAUNCH_CLASS $GLUE_CONF_DIR/exec.groovy $GLUE_CONF_DIR/modules.groovy"
  
  nohup $RUN_CMD > "$LOG" 2>&1 < /dev/null &
  RETVAL=$?
  echo $! > $PIDFILE

  sleep 2; tail "$LOG"

  return $RETVAL
}


stopGlueServer(){

   #stop glue server via the client first
   RUN_CMD="$JAVA $JAVA_HEAP $JAVA_OPTS -classpath "$CLASSPATH" $CLIENT_CLASS -stop"  

   exec $RUN_CMD 

   sleep 5s

   #check if still running after client command was called
   checkIfRunning
   ISRUNNING=$?


   if [ $ISRUNNING == 0  ]; then
     echo "glue-server is still running"
     exit 1
   fi 

  
}


exitIfRunning(){
 # Check to see if the glue server is running
 # if so this function calls exit 1

 PID=$(pgrep -f $LAUNCH_CLASS)

 if [ ! -z $PID ]; then
   echo "glue-server is running $PID"
   exit 1
 fi

}

checkIfRunning(){
  #if the glue server is running this script will return 0 else 1
  RETVAL=0
  PID=$(pgrep -f $LAUNCH_CLASS)

  if [ -z $PID ]; then
   RETVAL=1
  fi   

  return $RETVAL
}

start() {

          #this method will exit if running
          exitIfRunning
          
          echo -n "Starting : glue-server"

          startGlueServer
          RETVAL=$?
          checkIfRunning
          ISRUNNING=$?

          if [[ $RETVAL == 0 &&  $ISRUNNING == 0 ]]; then
           touch $LOCKFILE
          else
            echo -n "glue-server could not be started"
          fi

        echo        
        return $RETVAL
}

stop() {

        checkIfRunning
        ISRUNNING=$?
        if [ $ISRUNNING == 0 ]; then
          echo -n "Shutting down : glue-server "
         
         stopGlueServer         
         rm -f $LOCKFILE
         
        else
          echo -n "glue-server is not running"
        fi

        echo
        return 0
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status glue-server
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: glue-server  {start|stop|status|reload|restart[|probe]"
        exit 1
        ;;
esac
exit $?
